### ISSUE TITLE
main mission file may be missing 

### ISSUE THREAD

**Issue by darkangrycoder** [ilychkov/gta-vc-new-adventure-mod#1]
copy main.scm to the Data directory in your GTA: Vice City folder
copy american.gxt to the Text directory in your GTA: Vice City folde

I couldn't find  main.scm & american.gxt. May you please help me to find them?

**Comment by ilychkov** [comment]
Just download the latest version from the releases tab: https://github.com/ilychkov/gta-vc-mafia-takes-over-mod/releases
